### ISSUE TITLE
Can I run also the Three.js Editor inside node.js

### ISSUE THREAD

**Issue by jimver04** [Mugen87/three-jsm#12]
Hi,

this repo is just a demo for a very simple application. What about more complex applications such as the /three.js/editor . Can I run it in a similar way?

Can I use node.js http-server for the file serving parts in parallel (e.g. glb loading)?

Best,
Dimitrios

**Comment by Mugen87** [comment]
> Can I run it in a similar way?

Yes. When you download the repository, you can save the contents in your project's root directory and let them serve via your local web server.

> Can I use node.js http-server for the file serving parts in parallel (e.g. glb loading)?

Yes.
