### ISSUE TITLE
unable to update app

### ISSUE THREAD

**Issue by schwyzl** [Mugen87/three-jsm#3]
Hi, I am modifying app.js and nothing is updating... Even if I delete the animate() call or even delete the entire app dir, the server still boots up and displays the interactive cube. Not sure where the cube is being drawn if not by app.js...?

**Comment by andreaabellera** [comment]
Enter npm run-script build before you do npm start, that made it work for me. Though, you may have to do it for every change made.

**Comment by Mugen87** [comment]
For all devs stumble across this issue I recommend to enhance the `scripts` section in the `package.json` by this:
```
"dev": "concurrently \"rollup -c \"rollup_config.js\" -w\" \"serve\"",
```
and then change the `start` script to:
```
npm run dev
```
This will allow you to run two commands concurrently (the rebuild and the server process). You have to install the respective [npm](https://www.npmjs.com/package/concurrently) package however.
