### ISSUE TITLE
Newbie wants to know how to refresh app

### ISSUE THREAD

**Issue by GothParrot** [Mugen87/three-jsm#8]
Hi, thanks for the repo!! Sorry for the absolute beginner q. New to js dev. When I make changes to App.js, how can I refresh the app?

**Comment by Mugen87** [comment]
Sorry for the late reply. I've seen this issue just today.

When using rollup, you can use the `- w` option, see https://rollupjs.org/guide/en/#-w--watch.

We also use that in `three.js` when you run the `dev` script.
